name: Release Package to PyPI
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('./poetry.lock') }}

      - name: Install Dependencies if cache doesn't hit
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Publish to PyPI
        run:
          poetry config http-basic.pypi ${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI_PASSWORD }};
          poetry run invoke release ${{ github.event.release.name }}
